version: '3.8'

services:
  pentest-chatbot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pentest-knowledge-assistant
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET}
      - LITERAL_API_KEY=${LITERAL_API_KEY}
    volumes:
      - ./data:/app/data:ro
      - ./storage:/app/storage
      - ./public:/app/public:ro
      - chatbot_cache:/root/.chatbot_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot-network

volumes:
  chatbot_cache:
    driver: local

networks:
  chatbot-network:
    driver: bridge